/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_fleece_FLSliceResult_UnmanagedFLSliceResult */

#ifndef _Included_com_couchbase_lite_internal_fleece_FLSliceResult_UnmanagedFLSliceResult
#define _Included_com_couchbase_lite_internal_fleece_FLSliceResult_UnmanagedFLSliceResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
