/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_core_C4TestUtils */

#ifndef _Included_com_couchbase_lite_internal_core_C4TestUtils
#define _Included_com_couchbase_lite_internal_core_C4TestUtils
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    getPrivateUUID
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_getPrivateUUID
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    encodeJSON
 * Signature: (J[B)Lcom/couchbase/lite/internal/fleece/FLSliceResult;
 */
JNIEXPORT jobject JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_encodeJSON
        (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    enumerateAllDocs
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_enumerateAllDocs
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    next
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_next
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    getDocument
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_getDocument
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4TestUtils_free
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    getDocID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_couchbase_lite_internal_core_C4TestUtils_getDocID
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    put
 * Signature: (J[BLjava/lang/String;IZZ[Ljava/lang/String;ZII)J
 */
JNIEXPORT jlong JNICALL
Java_com_couchbase_lite_internal_core_C4TestUtils_put
        (JNIEnv *, jclass, jlong, jbyteArray, jstring, jint, jboolean, jboolean, jobjectArray, jboolean, jint, jint);

/*
 * Class:     com_couchbase_lite_internal_core_C4TestUtils
 * Method:    put2
 * Signature: (JJLjava/lang/String;IZZ[Ljava/lang/String;ZII)J
 */
JNIEXPORT jlong JNICALL
Java_com_couchbase_lite_internal_core_C4TestUtils_put2
        (JNIEnv *, jclass, jlong, jlong, jlong, jstring, jint, jboolean, jboolean, jobjectArray, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
