/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_core_C4BlobStore_ManagedC4BlobStore */

#ifndef _Included_com_couchbase_lite_internal_core_C4BlobStore_ManagedC4BlobStore
#define _Included_com_couchbase_lite_internal_core_C4BlobStore_ManagedC4BlobStore
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
