/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_core_C4Log_RawLog */

#ifndef _Included_com_couchbase_lite_internal_core_C4Log_RawLog
#define _Included_com_couchbase_lite_internal_core_C4Log_RawLog
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
