/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_fleece_FLSliceResult */

#ifndef _Included_com_couchbase_lite_internal_fleece_FLSliceResult
#define _Included_com_couchbase_lite_internal_fleece_FLSliceResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_fleece_FLSliceResult
 * Method:    getBuf
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_fleece_FLSliceResult_getBuf
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_internal_fleece_FLSliceResult
 * Method:    release
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_fleece_FLSliceResult_release(
        JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
