/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_fleece_FLEncoder_ManagedFLEncoder */

#ifndef _Included_com_couchbase_lite_internal_fleece_FLEncoder_ManagedFLEncoder
#define _Included_com_couchbase_lite_internal_fleece_FLEncoder_ManagedFLEncoder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
