/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_core_C4Replicator */

#ifndef _Included_com_couchbase_lite_internal_core_C4Replicator
#define _Included_com_couchbase_lite_internal_core_C4Replicator
#ifdef __cplusplus
extern "C" {
#endif
#undef com_couchbase_lite_internal_core_C4Replicator_PROGRESS_OVERALL
#define com_couchbase_lite_internal_core_C4Replicator_PROGRESS_OVERALL 0L
#undef com_couchbase_lite_internal_core_C4Replicator_PROGRESS_PER_DOC
#define com_couchbase_lite_internal_core_C4Replicator_PROGRESS_PER_DOC 1L
#undef com_couchbase_lite_internal_core_C4Replicator_PROGRESS_PER_ATTACHMENT
#define com_couchbase_lite_internal_core_C4Replicator_PROGRESS_PER_ATTACHMENT 2L
/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    create
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;IIJIJZZ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_create
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jstring, jstring, jint, jint, jlong, jint, jlong, jboolean, jboolean, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    createLocal
 * Signature: (JJIIJZZ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_createLocal
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jboolean , jboolean , jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    createWithSocket
 * Signature: (JJII[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_createWithSocket
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    start
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_start
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    setOptions
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_setOptions
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    getStatus
 * Signature: (J)Lcom/couchbase/lite/internal/core/C4ReplicatorStatus;
 */
JNIEXPORT jobject JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_getStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    getPendingDocIds
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_getPendingDocIds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    isDocumentPending
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_isDocumentPending
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    setProgressLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_setProgressLevel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_internal_core_C4Replicator
 * Method:    setHostReachable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_core_C4Replicator_setHostReachable
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
